insert into services (name, plan_name, monthly_price, value_score) values
  ('Netflix',           'Standard with Ads', 7.99,  7.2),
  ('Netflix',           'Standard',          15.49, 6.8),
  ('Netflix',           'Premium',           22.99, 6.1),
  ('Hulu',              'With Ads',          7.99,  7.5),
  ('Hulu',              'No Ads',            17.99, 6.9),
  ('Disney+',           'With Ads',          7.99,  7.8),
  ('Disney+',           'Premium',           13.99, 7.1),
  ('Max',               'With Ads',          9.99,  7.0),
  ('Max',               'Ad-Free',           15.99, 6.5),
  ('Paramount+',        'Essential',         5.99,  6.8),
  ('Paramount+',        'With Showtime',     11.99, 6.3),
  ('Peacock',           'Free',              0.00,  8.5),
  ('Peacock',           'Premium',           7.99,  7.0),
  ('Peacock',           'Premium Plus',      13.99, 6.4),
  ('Apple TV+',         'Standard',          9.99,  7.6),
  ('Amazon Prime Video','Standard',          8.99,  7.9),
  ('Spotify',           'Individual',        11.99, 8.2),
  ('YouTube Premium',   'Individual',        13.99, 7.3);
